### ISSUE TITLE
请问「java.lang.String com.wayne.baiduvoice.util.OfflineResource.getTextFilename()」为 null 是什么原因？

### ISSUE THREAD

**Issue by Kennytian** [wayne214/react-native-baidu-voice#3]
电脑环境：
```
System:
    OS: macOS 10.15.1
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 16, 21, 23, 25, 28, 29
      Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

```

报错信息：
```
12-26 16:37:12.311 14862-14885/com.anlint.weightapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.anlint.weightapp, PID: 14862
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.wayne.baiduvoice.util.OfflineResource.getTextFilename()' on a null object reference
        at com.wayne.baiduvoice.VoiceUtils.getParams(VoiceUtils.java:175)
        at com.wayne.baiduvoice.VoiceUtils.initialTts(VoiceUtils.java:83)
        at com.wayne.baiduvoice.VoiceUtils.init(VoiceUtils.java:65)
        at com.wayne.baiduvoice.RNBaiduvoiceModule.initBaiduTTS(RNBaiduvoiceModule.java:32)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by wayne214** [comment]
您好，抱歉给你的使用带来了麻烦，是Android10系统的存储权限导致的，现在已经修复了，可以更新一下组件版本，再试一下。感谢你的支持。

**Comment by wayne214** [comment]
> 电脑环境：
> 
> ```
> System:
>     OS: macOS 10.15.1
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 12.13.0 - /usr/local/bin/node
>     Yarn: 1.19.1 - ~/.yarn/bin/yarn
>     npm: 6.12.0 - /usr/local/bin/npm
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
>     Android SDK:
>       API Levels: 16, 21, 23, 25, 28, 29
>       Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0
>       System Images: android-21 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
>   IDEs:
>     Android Studio: 3.5 AI-191.8026.42.35.5977832
>     Xcode: 10.3/10G8 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.9.0 => 16.9.0 
>     react-native: 0.61.5 => 0.61.5
> ```
> 
> 报错信息：
> 
> ```
> 12-26 16:37:12.311 14862-14885/com.anlint.weightapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
>     Process: com.anlint.weightapp, PID: 14862
>     java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.wayne.baiduvoice.util.OfflineResource.getTextFilename()' on a null object reference
>         at com.wayne.baiduvoice.VoiceUtils.getParams(VoiceUtils.java:175)
>         at com.wayne.baiduvoice.VoiceUtils.initialTts(VoiceUtils.java:83)
>         at com.wayne.baiduvoice.VoiceUtils.init(VoiceUtils.java:65)
>         at com.wayne.baiduvoice.RNBaiduvoiceModule.initBaiduTTS(RNBaiduvoiceModule.java:32)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
>         at android.os.Looper.loop(Looper.java:148)
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
>         at java.lang.Thread.run(Thread.java:818)
> ```
您好，抱歉给你的使用带来了麻烦，是Android10系统的存储权限导致的，现在已经修复了，可以更新一下组件版本，再试一下。感谢你的支持。
